kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: registry.gitlab.com/dhandspikerwade/video-recorder
    tags: latest