kind: pipeline
type: docker
name: default

steps:
- name: Build & publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    registry: registry.gitlab.com
    repo: registry.gitlab.com/dhandspikerwade/video-recorder
    tags: latest
    dry_run: false
  when:
    branch:
    - master

- name: Build & publish Experimental
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    registry: registry.gitlab.com
    repo: registry.gitlab.com/dhandspikerwade/video-recorder
    tags: kube-experimental
    dry_run: false
  when:
    branch:
    - master

# Just test build branches
- name: Build  
  image: plugins/docker
  settings:
    repo: registry.gitlab.com/dhandspikerwade/video-recorder
    tags: latest
    dry_run: true
  when:
    branch:
      exclude:
      - master