steps:
- name: Build & publish  
  image: woodpeckerci/plugin-docker-buildx
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    registry: registry.gitlab.com
    repo: registry.gitlab.com/dhandspikerwade/video-recorder
    tags: latest
    dry_run: false
  when:
    branch:
    - master

- name: Build & publish Experimental
  image: woodpeckerci/plugin-docker-buildx
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    registry: registry.gitlab.com
    repo: registry.gitlab.com/dhandspikerwade/video-recorder
    tags: kube-experimental
    dry_run: false
  when:
    branch:
    - kube-experimental

# Just test build branches
- name: Build  
  image: woodpeckerci/plugin-docker-buildx
  settings:
    repo: registry.gitlab.com/dhandspikerwade/video-recorder
    tags: latest
    dry_run: true
  when:
    branch:
      exclude:
      - master
      - kube-experimental